"""
=============================================================================
MASTER RUNNER - Earnings Volatility Backtest Pipeline
=============================================================================

Runs the full pipeline in order:
    Step 1: backtest_v2.py           → Backtest + capital management
    Step 2: generate_charts_v2.py    → Professional charts (3 PNGs)

Requirements:
    pip install pandas numpy scipy matplotlib

Input files (must be in data/ directory):
    - earnings_data_FINAL.csv   (420 earnings events)
    - price_data_FINAL.csv      (30,330 daily OHLCV records)

Output files:
    - backtest_v2_flat.csv          (420 trades, flat IV model)
    - backtest_v2_skew.csv          (420 trades, skew IV model)
    - backtest_v2_metrics.json      (portfolio metrics)
    - equity_flat.npy               (equity curve array)
    - equity_skew.npy               (equity curve array)
    - backtest_v2_dashboard.png     (6-panel dashboard)
    - backtest_v2_annual.png        (annual performance)
    - backtest_v2_skew_analysis.png (skew comparison)
=============================================================================
"""

import time
import os
import sys

def run_step(description, module_name):
    """Run a step and measure time."""
    print(f"\n{'='*70}")
    print(f"  STEP: {description}")
    print(f"{'='*70}\n")
    
    start = time.time()
    
    # Import and run the module's main block
    try:
        if module_name == 'backtest_v2':
            import backtest_v2
            # Re-run the backtest logic
            import pandas as pd
            import numpy as np
            
            earnings = pd.read_csv('data/earnings_data_FINAL.csv')
            prices = pd.read_csv('data/price_data_FINAL.csv')
            print(f"Loaded: {len(earnings)} earnings, {len(prices)} price records\n")
            
            # Run flat IV
            results_flat, equity_flat = backtest_v2.run_backtest_v2(
                earnings, prices.copy(), use_skew=False
            )
            # Run with skew
            results_skew, equity_skew = backtest_v2.run_backtest_v2(
                earnings, prices.copy(), use_skew=True
            )
            
            # Compute metrics
            metrics_flat = backtest_v2.compute_portfolio_metrics(results_flat, equity_flat)
            metrics_skew = backtest_v2.compute_portfolio_metrics(results_skew, equity_skew)
            
            # Save
            results_flat.to_csv('backtest_v2_flat.csv', index=False)
            results_skew.to_csv('backtest_v2_skew.csv', index=False)
            
            import json
            with open('backtest_v2_metrics.json', 'w') as f:
                json.dump({
                    'flat': {k: float(v) if isinstance(v, (np.floating, np.integer)) else v
                            for k, v in metrics_flat.items()},
                    'skew': {k: float(v) if isinstance(v, (np.floating, np.integer)) else v
                            for k, v in metrics_skew.items()}
                }, f, indent=2, default=str)
            
            np.save('equity_flat.npy', equity_flat)
            np.save('equity_skew.npy', equity_skew)
            
            print("\nSaved: backtest_v2_flat.csv, backtest_v2_skew.csv")
            print("Saved: backtest_v2_metrics.json, equity curves")
        
        elif module_name == 'generate_charts_v2':
            import generate_charts_v2
            results_flat, results_skew, equity_flat, equity_skew, metrics = \
                generate_charts_v2.load_data()
            
            generate_charts_v2.plot_main_dashboard(results_flat, equity_flat, metrics['flat'])
            generate_charts_v2.plot_skew_analysis(
                results_flat, results_skew, equity_flat, equity_skew, metrics
            )
            generate_charts_v2.plot_annual_performance(results_flat, metrics['flat'])
        
        
        elapsed = time.time() - start
        print(f"\n  Completed in {elapsed:.1f} seconds")
        return True
        
    except Exception as e:
        print(f"\n  ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False


def check_inputs():
    """Verify all required input files exist."""
    required = ['data/earnings_data_FINAL.csv', 'data/price_data_FINAL.csv']
    missing = [f for f in required if not os.path.exists(f)]
    
    if missing:
        print("ERROR: Missing input files:")
        for f in missing:
            print(f"  - {f}")
        print("\nThese files should be in the same directory as this script.")
        print("They are generated by collect_data_simple.py (see project README).")
        return False
    return True


def check_dependencies():
    """Verify all Python packages are installed."""
    packages = {
        'pandas': 'pandas',
        'numpy': 'numpy',
        'scipy': 'scipy',
        'matplotlib': 'matplotlib',
    }
    
    missing = []
    for import_name, pip_name in packages.items():
        try:
            __import__(import_name)
        except ImportError:
            missing.append(pip_name)
    
    if missing:
        print("ERROR: Missing Python packages:")
        print(f"  pip install {' '.join(missing)}")
        return False
    return True


if __name__ == "__main__":
    
    print("=" * 70)
    print("  EARNINGS VOLATILITY BACKTEST - FULL PIPELINE")
    print("=" * 70)
    
    total_start = time.time()
    
    # Pre-flight checks
    if not check_dependencies():
        sys.exit(1)
    if not check_inputs():
        sys.exit(1)
    
    print("\nAll checks passed. Starting pipeline...\n")
    
    # Step 1: Backtest
    ok = run_step("Backtest V2 (flat IV + skew)", "backtest_v2")
    if not ok:
        print("\nBacktest failed. Fix errors above and re-run.")
        sys.exit(1)
    
    # Step 2: Charts
    ok = run_step("Generate Charts (3 PNGs)", "generate_charts_v2")
    if not ok:
        print("\nChart generation failed. Fix errors above and re-run.")
        sys.exit(1)
    
    
    # Summary
    total_elapsed = time.time() - total_start
    
    print("\n" + "=" * 70)
    print("  PIPELINE COMPLETE")
    print("=" * 70)
    print(f"\n  Total time: {total_elapsed:.0f} seconds ({total_elapsed/60:.1f} minutes)")
    print(f"\n  Output files:")
    
    outputs = [
        'backtest_v2_flat.csv',
        'backtest_v2_skew.csv',
        'backtest_v2_metrics.json',
        'docs/backtest_v2_dashboard.png',
        'docs/backtest_v2_annual.png',
        'docs/backtest_v2_skew_analysis.png',
    ]
    
    for f in outputs:
        if os.path.exists(f):
            size = os.path.getsize(f)
            if size > 1_000_000:
                print(f"    {f}  ({size/1_000_000:.1f} MB)")
            else:
                print(f"    {f}  ({size/1_000:.0f} KB)")
        else:
            print(f"    {f}  (NOT FOUND)")
    
    print(f"\n  Done.")
